name: Continuous Integration
on:
  push:
  pull_request:

jobs:
  analysis:
    name: Code format check
    runs-on: Windows-latest
    
    steps:
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@v1
        id: code-analysis
        with:
          solution: MySolution.sln
          build-breaking: true
          all-categories: all
